language: node_js
branches:
  only:
    - master
install:
  - npm install
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run build
after_success:
  - npm run deploy-docs
  - npm run semantic-release
